config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "home/About"
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user, optional: true
	has_attached_file :image, styles: { medium: "500x500>", thumb: "700x700>",  }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:edit, :update, :destroy]
  # GET /books
  # GET /books.json
  def index
    @books = Book.all.order("created_at DESC")
    
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
  end

  # GET /books/new
  def new
    #@book = Book.new
    @book = current_user.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    #@book = Book.new(book_params)
    @book = current_user.books.build(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:image, :book_name, :Author, :seller_name, :price, :tel_number, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def About
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: {multipart: true } do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 

  <div class="form-group">
  
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :book_name %>
    <%= form.text_field :book_name , class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :Author %>
    <%= form.text_field :Author, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :seller_name %>
    <%= form.text_field :seller_name, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :tel_number %>
    <%= form.text_field :tel_number, class: "form-control form-control-lg" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Book", class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<div class="dd">
<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<head>

  <link rel="stylesheet" type="text/css" href="index style.css">
  <link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
  <link rel="icon" type="image/PNG" href="backgrounds/Untitled-6.png">

  <title>Book a Book</title>


</head>


<div class="dd">
  <p id="notice"><%= notice %></p>

<h1>Books</h1></br></br>
  <div class="card-deck">
    <% @books.each do |book| %>
      <div class="col-md-3">
      <div class="card">
        <%= link_to image_tag(book.image.url(:medium)), book, class: 'card-img-top'  %> 
        <div class="card-body">
           <h5 class="card-title"><%= book.book_name %></h5>
              
            <%= book.Author %> </br>     
          <strong>Price:</strong><%= book.price %>
          <div class="card-footer">
          <% if user_signed_in? %>
            <% if book.user.id == current_user.id %>
              <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <% end %>
        </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="jumbotron jumbotron-fluid">
  <div class="dd">
   <h1 class="display-4">Add A book Now!</h1>

   <%= link_to 'New Book', new_book_path, class: 'btn btn-primary'%> 
  </div>
</div>

app/views/books/new.html.erb
<head>

	<link rel="stylesheet" type="text/css" href="index style.css">
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
	<link rel="icon" type="image/PNG" href="backgrounds/Untitled-6.png">

	<title>Book a Book</title>

	<script type="text/javascript"
	>$(function () {
	  $(document).scroll(function () {
	    var $nav = $(".navbar-fixed-top");
	    $nav.toggleClass('scrolled', $(this).scrollTop() > $nav.height());
	  });
	});
	</script>


</head>
<div class="dd">
	
<h1>New Book </h1>

<div class="informations">
<%= render 'form', book: @book %>
</div>
</div>
<div class="jumbotron jumbotron-fluid">
  <div class="dd">
   <h1 class="display-4">Don't forgit to delete the Book After the DEAL!</h1>
   <%= link_to 'Back', books_path, class: 'btn btn-primary'%> 
  </div>
</div>

app/views/books/show.html.erb
<div class="dd">

<p id="notice"><%= notice %></p>

<div class="dv">
  <p>  
    <%=image_tag @book.image.url(:thumb) %>
  </p>
</div></br></br></br></br>

<p class="db">Get this book!!</p></br></br></br></br></br></br>
<div class="dp">
<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.Author %>
</p>

<p>
  <strong>Seller name:</strong>
  <%= @book.seller_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Tel number:</strong>
  <%= @book.tel_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @book.address %>
</p>
        <% if user_signed_in? %>
          <% if @book.user == current_user %>
            <%= link_to 'Edit', edit_book_path(@book) %> 
          <% end %>
        <% end %></br></br></br></br></br></br>
</div>
</div>

<div class="jumbotron jumbotron-fluid">
  <div class="dd">
   <%= link_to 'Back', books_path, class: 'btn btn-primary'%> 
</div>
</div>

app/views/home/About.html.erb
<html>

<head>

	<link rel="stylesheet" type="text/css" href="index style 2.css">
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>
	<link rel="icon" type="image/PNG" href="backgrounds/Untitled-6.png">


	<title>ABOUT</title>

	
</head>

<body>

<div class="jumbotron">
  <h1 class="display-4">Book a Book</h1>
		
	<h2 class="lead">This is a web-based application project under supervision of Dr. Amal Professorin Computer and Systems Engineering department.</h2>
 	 <hr class="my-4">
	<ul>
		<font size="6"><li>ziadhesham97@gmail.com</li></font>
		<font size="6"><li>usseif97@gmail.com</li></font>
		<font size="6"><li>AhmedEzeny@gmail.com</li></font>
		<font size="6"><li>mosyoui@gmail.com</li></font>
	</ul>

</div>


</body>

</html>

app/views/home/index.html.erb
<html>

<head>

	<link rel="stylesheet" type="text/css" href="index style.css">
	<link rel="stylesheet" type="text/css" href="dynamic.css">
	<link rel="stylesheet" type="text/javascript" href="dynamic.js">
	<link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>

	<title>Book a Book</title>



</head>

<body>
	<%= image_tag("books_library_old_111388_1920x1080.jpg") %>
	<div class="description">
	  <div class="parallax"></div>
		<div class="blurredbackground"></div>

		<p><span class="Reading">Reading</span><span class="firstLine"> books hasn't been easier,<br>
		You don't have an Excuse not to read<br>
		Find now books for your favorite author with ease.</span><br><br><br><br><br>
		<%= image_tag("2.jpg") %><br><br><br><br><br>
		<span class="choosing">Choose</span> the way you want to read your favourite books.<br>  Borrow, Buy and Benefit from your old books</p>
		<br><br><br><br><br>
		<%= image_tag("3.jpg") %><br>
		<div class="jumbotron jumbotron-fluid">
		  <div class="dd">
			<% if user_signed_in? %>

				<%= link_to 'logout', destroy_user_session_path,:method => 'delete' , method: :delete, class: 'btn btn-primary'%>
				<%= link_to 'List Books', books_path , class: 'btn btn-primary'%></br></br>
			<% else %>
				<h1 class="display-4">Join Us Now</h1>
				<%= link_to 'login', new_user_session_path , class: 'btn btn-primary'%>
				<%= link_to 'join', new_user_registration_path, class: 'btn btn-primary'%></br></br>
			<% end %>
		  </div>
		</div>
  </div>
  </div>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book A Book</title>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag "jquery_ujs" %>
    <link rel="stylesheet" type="text/css" href="index style.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css' %>
  </head>

  <body>
    
    <nav class="navBar">
        <a class="tit" >Book a Book <i class="icon"></i></a>
        <ul> <%= link_to "Home" , home_index_path %> </ul>
        <ul> <%= link_to "Buy/Borrow" , books_path %> </ul>
        <ul> <%= link_to "Sell/Lend" , new_book_path %> </ul>
        <a class="about" <%= link_to "About Us" , home_About_path %></a>
        <a class="about" <%= link_to "Sign in" , new_user_session_path %></a>
      </nav>

        <div class="header">
         
         <div class="progress-container">
           <div class="progress-bar" id="myBar"></div>
         </div>
        </div>

    <div class="dd">
      <% flash.each do |name , msg| %>
        <%= content_tag( :div,msg, class: "alert alert-info")%>
      <% end %>
    </div>
    <%= yield %>
  
  
  </body>

</html>